# Reload tmux configuration using 'Ctrl+B r'
unbind r
bind r source-file ~/.tmux.conf 

# Enable color support for terminal while in tmux
set -g default-terminal "xterm-256color"
#set -ag terminal-overrides ",xterm-256color:Tc"

# Disable mouse support
# set -g mouse on

# Enable support for clipboard
set-option -s set-clipboard on

# Enable vim-like key bindings in copy mode
#set -g mode-keys vi

# Vim-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Increase session name length to 40 characters
#set -g status-left-length 40

# Enable clipboard integration
#set -g set-clipboard on

# Allow pasting using the terminal's clipboard
#bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

# Use system clipboard directly for copy-paste (for TigerVNC clipboard sync)
#bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"

# Ensure new panes and windows open in the same directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Ensure .bashrc is sourced
#set-option -g default-command "bash --rcfile ~/.bashrc"

